// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251226122224_InitialCreateTodo")]
    partial class InitialCreateTodo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("todo")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CalendarEntityCalendarLinkEntity", b =>
                {
                    b.Property<Guid>("CalendarLinksId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_links_id");

                    b.Property<Guid>("CalendarsId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendars_id");

                    b.HasKey("CalendarLinksId", "CalendarsId")
                        .HasName("pk_calendar_entity_calendar_link_entity");

                    b.HasIndex("CalendarsId")
                        .HasDatabaseName("ix_calendar_entity_calendar_link_entity_calendars_id");

                    b.ToTable("calendar_entity_calendar_link_entity", "todo");
                });

            modelBuilder.Entity("Database.Entity.CalendarEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastSelectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_selected_at");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1028)
                        .HasColumnType("character varying(1028)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_calendar");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_calendar_owner_id");

                    b.HasIndex("OwnerId", "Id")
                        .HasDatabaseName("ix_calendar_owner_id_id");

                    b.ToTable("calendar", "todo");
                });

            modelBuilder.Entity("Database.Entity.CalendarLinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalendarLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("calendar_link");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1028)
                        .HasColumnType("character varying(1028)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_calendar_link");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_calendar_link_user_id");

                    b.ToTable("calendar_link", "todo");
                });

            modelBuilder.Entity("Database.Entity.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(32896)
                        .HasColumnType("character varying(32896)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1028)
                        .HasColumnType("character varying(1028)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_event");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_event_created_by_id");

                    b.HasIndex("CalendarId", "Id")
                        .HasDatabaseName("ix_event_calendar_id_id");

                    b.HasIndex("CalendarId", "StartsAt", "EndsAt")
                        .HasDatabaseName("ix_event_calendar_id_starts_at_ends_at");

                    b.ToTable("event", "todo");
                });

            modelBuilder.Entity("Database.Entity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("ProfileImageLarge")
                        .HasColumnType("text")
                        .HasColumnName("profile_image_large");

                    b.Property<string>("ProfileImageMedium")
                        .HasColumnType("text")
                        .HasColumnName("profile_image_medium");

                    b.Property<string>("ProfileImageSmall")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_image_small");

                    b.Property<Guid?>("SelectedCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_calendar_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("SelectedCalendarId")
                        .HasDatabaseName("ix_user_selected_calendar_id");

                    b.ToTable("user", "todo");
                });

            modelBuilder.Entity("CalendarEntityCalendarLinkEntity", b =>
                {
                    b.HasOne("Database.Entity.CalendarLinkEntity", null)
                        .WithMany()
                        .HasForeignKey("CalendarLinksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_entity_calendar_link_entity_calendar_link_calendar");

                    b.HasOne("Database.Entity.CalendarEntity", null)
                        .WithMany()
                        .HasForeignKey("CalendarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_entity_calendar_link_entity_calendar_calendars_id");
                });

            modelBuilder.Entity("Database.Entity.CalendarEntity", b =>
                {
                    b.HasOne("Database.Entity.UserEntity", "Owner")
                        .WithMany("Calendars")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_calendar_user_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Database.Entity.CalendarLinkEntity", b =>
                {
                    b.HasOne("Database.Entity.UserEntity", "User")
                        .WithMany("CalendarLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_link_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Entity.EventEntity", b =>
                {
                    b.HasOne("Database.Entity.CalendarEntity", "Calendar")
                        .WithMany("Events")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_calendar_calendar_id");

                    b.HasOne("Database.Entity.UserEntity", "CreatedBy")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_user_created_by_id");

                    b.Navigation("Calendar");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Database.Entity.UserEntity", b =>
                {
                    b.HasOne("Database.Entity.CalendarEntity", null)
                        .WithMany()
                        .HasForeignKey("SelectedCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_calendar_selected_calendar_id");
                });

            modelBuilder.Entity("Database.Entity.CalendarEntity", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Database.Entity.UserEntity", b =>
                {
                    b.Navigation("CalendarLinks");

                    b.Navigation("Calendars");

                    b.Navigation("CreatedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
