// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251221123542_InitialSharedCalendar")]
    partial class InitialSharedCalendar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("todo")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Database.Entity.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(32896)
                        .HasColumnType("character varying(32896)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("HostedById")
                        .HasColumnType("uuid")
                        .HasColumnName("hosted_by_id");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1028)
                        .HasColumnType("character varying(1028)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_event");

                    b.HasIndex("HostedById")
                        .HasDatabaseName("ix_event_hosted_by_id");

                    b.ToTable("event", "todo");
                });

            modelBuilder.Entity("Database.Entity.SharedCalendarEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalendarLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("calendar_link");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_shared_calendar");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_shared_calendar_user_id");

                    b.ToTable("shared_calendar", "todo");
                });

            modelBuilder.Entity("Database.Entity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("ProfileImageLarge")
                        .HasColumnType("text")
                        .HasColumnName("profile_image_large");

                    b.Property<string>("ProfileImageMedium")
                        .HasColumnType("text")
                        .HasColumnName("profile_image_medium");

                    b.Property<string>("ProfileImageSmall")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_image_small");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", "todo");
                });

            modelBuilder.Entity("Database.Entity.EventEntity", b =>
                {
                    b.HasOne("Database.Entity.UserEntity", "HostedBy")
                        .WithMany("HostedEvents")
                        .HasForeignKey("HostedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_user_hosted_by_id");

                    b.Navigation("HostedBy");
                });

            modelBuilder.Entity("Database.Entity.SharedCalendarEntity", b =>
                {
                    b.HasOne("Database.Entity.UserEntity", "User")
                        .WithMany("SharedCalendars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shared_calendar_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Entity.UserEntity", b =>
                {
                    b.Navigation("HostedEvents");

                    b.Navigation("SharedCalendars");
                });
#pragma warning restore 612, 618
        }
    }
}
